---

- apt: name=curl state=present

# ﻿[WARNING]: Consider using get_url or uri module rather than running curl
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: /tmp

- name: move composer
  shell: mv /tmp/composer.phar /usr/local/bin/composer
