---

- user:
   name: "{{ php_laravel_user }}"
   state: present
   createhome: yes

- shell: composer global require "laravel/installer=~1.1"
  when: php_install_composer
  become: yes
  become_user: "{{ php_laravel_user }}"

- stat: path=~/.zshrc
  register: php_zshrc
  become: yes
  become_user: "{{ php_laravel_user }}"

# Make sure to place the ~/.composer/vendor/bin directory in your PATH so the laravel executable can be located by your system.
- lineinfile: dest=~/.zshrc line="alias laravel=\"~/.composer/vendor/bin/laravel\"" state=present
  become: yes
  become_user: "{{ php_laravel_user }}"
  when: php_zshrc.stat.exists == True
