---
# tasks file for php

- apt: name=apt-transport-https update_cache=yes state=latest

# Jessie
- include: main-debian8-php7.yml
  when: ansible_distribution == 'Debian'
        and ansible_distribution_major_version == '8'
        and php_major_version == 7

# Stretch
- include: main-debian9-php7.yml
  when: ansible_distribution == 'Debian'
        and ansible_distribution_major_version == '9'
        and php_major_version == 7

# Various
- include: composer.yml
  when: php_install_composer

- include: laravel.yml
  when: php_install_laravel
