---

- apt_key: url=https://packages.sury.org/php/apt.gpg state=present

- apt_repository: repo='deb https://packages.sury.org/php/ stretch main' state=present

- apt_repository: repo='deb-src https://packages.sury.org/php/ stretch main' state=present

- include: debian-php7.yml
